project:
  type: website

website:
  title: "Max Worgan's PhD research blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/MaxWorgan
format:
  html:
    theme: simplex
    css: styles.css



